# Created using winget-create 1.6.0.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: scottkw.StorCat
PackageVersion: 1.2.3
InstallerType: portable
Commands:
- storcat
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/scottkw/storcat/releases/download/1.2.3/StorCat.1.2.3.exe
  InstallerSha256: 📥 Downloading: https://github.com/scottkw/storcat/releases/download/1.2.3/StorCat.1.2.3.exe
cd9e1c2ba9d44676393580b9274c1134182b496db44d7039e1aa64e3e644b3ed
ManifestType: installer
ManifestVersion: 1.6.0
