# Created using winget-create 1.6.0.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: scottkw.StorCat
PackageVersion: 1.1.2
InstallerType: portable
Commands:
- storcat
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/scottkw/storcat/releases/download/1.1.2/StorCat.1.1.2.exe
  InstallerSha256: 📥 Downloading: https://github.com/scottkw/storcat/releases/download/1.1.2/StorCat.1.1.2.exe
7e6c2ad8bb7320edbe50bd790e9356e99109abf45633b0b0ec40ae6941c02132
ManifestType: installer
ManifestVersion: 1.6.0
